### ISSUE TITLE
Advanced Option to "Accept Registration" also sends the configuration

### ISSUE THREAD

**Issue by ChrScha** [SoftwareAG/cumulocity-flexy-integration-ui#19]
![image](https://github.com/SoftwareAG/cumulocity-flexy-integration-ui/assets/87694180/67bc3d75-ecc0-4a7c-8a0c-898cb6301b05)
![image](https://github.com/SoftwareAG/cumulocity-flexy-integration-ui/assets/87694180/7cc188a0-52c4-40c3-bf81-a648abb0c25a)

**Comment by dirk-peter-c8y** [comment]
it is not sending; that is just a delay (sleep) in between steps.
#16 will change the check to only apply the delay if both, "send connection config" and "accept device registration", are selected.
