### ISSUE TITLE
Investigate Feasibility for having a Dropdown List for Available Connector Versions

### ISSUE THREAD

**Issue by ChrScha** [SoftwareAG/cumulocity-flexy-integration-ui#20]
Currently the URLs need to be inserted to specify the files.
![image](https://github.com/SoftwareAG/cumulocity-flexy-integration-ui/assets/87694180/37c8b6bb-2824-4855-9a8e-3eb0881c7bde)
This is error prone as you have to edit the directory and file names.

**Comment by dirk-peter-c8y** [comment]
btw: still facing CORS issues

**Comment by dirk-peter-c8y** [comment]
Ian adjusted the API from HMS side to be accessible _from the outside_ – tested and confirmed.
I just prepared an update that adds a dropdown on top of the "file" fields, that provides an option to pick and chose an official release while maintaining the possibility for manual input.

![image](https://github.com/SoftwareAG/cumulocity-flexy-integration-ui/assets/67102395/efa581c6-c324-4958-ac64-c0b437353523)
