### ISSUE TITLE
add missing readme info how to include plugin in cloned app

### ISSUE THREAD

**Issue by dirk-peter-c8y** [SoftwareAG/cumulocity-flexy-integration-ui#25]

**Comment by ChrScha** [comment]
@dirk-peter-sag Please edit added images in the "apple highlighting style":
https://github.com/SoftwareAG/cumulocity-flexy-integration-ui/tree/ChrScha-patch-1/_media
![Image](https://github.com/SoftwareAG/cumulocity-flexy-integration-ui/assets/87694180/4ccbef7c-1246-45a5-b163-bcfb86da7d11)

**Comment by dirk-peter-c8y** [comment]
highlight added

**Comment by dirk-peter-c8y** [comment]
missing description and screenshot added to step three (thanks Chris).
also added missing image captions
