### ISSUE TITLE
Topics

### ISSUE THREAD

**Issue by switschel** [SoftwareAG/cumulocity-flexy-integration-ui#9]
Hi,

can you please add one or multiple of the following topics to your repo?
'agent' or 'cumulocity-agent'
'webapp' or 'cumulocity-webapp'
'widget' or 'cumulocity-widget'
'client' or 'cumulocity-client'
'cli' or 'cumulocity-cli'
'microservice' or 'cumulocity-microservice'
'example' or 'cumulocity-example'
'tutorial' or 'cumulocity-tutorial'
'simulator' or 'cumulocity-simulator'
'extension' or 'cumulocity-extension'

This is needed to get an overview about all open-source Cumulocity IoT Repos and make them visible on prominent pages.

**Comment by dirk-peter-c8y** [comment]
added `cumulocity-webapp`. sorry for the long wait.
